export function list_lang() { return ["en", "fr", "es", "pl", "id", "vi"] }

export function translate() {
	if (arguments[0] == "en") {
		return {
			error_arg: "§cWrong Arguments",
			error_find_player: "§cPlayer not found",
			db_update: "§6Database Updated",
			db_already_update: "§cDatabase already updated",
			unlock_admin_db: "§eAdmin database unlocked",
			lock_admin_db: "§eAdmin database locked",
			lock_error: "§cYou can't lock the admin database if you aren't inside",
			add_admin_error: "§cThis player is already Admin",
			add_admin: "§ePlayer added to Admin database",
			error_pass: "§cInvalid Password",
			remove_admin: "§ePlayer removed to Admin database",
			error_find_admin: "§cAdmin not found",
			unban: `§e${arguments[1]} is unban`,
			set_tpa_delay: `§eTpa delay set to ${arguments[1]} secondes`,
			error_number: `§cInvalid number`,
			add_display: "§eDisplay Added.",
			error_tag: `§cInvalid tag`,
			error_arg_display: `§cWrong Arguments (should be "title" or "actionbar")`,
			remove_display: `§eDisplay n°${arguments[1]} removed.`,
			error_find_display: `§cCan't find display (do ${arguments[1]}display list)`,
			error_number_display: `§cInvalid number (do ${arguments[1]}display list)`,
			error_arg_display2: `§cWrong Arguments (add|remove|list) expected`,
			set_Fhome_off: "§eFaction Home §cdenied",
			set_Fhome_on: "§eFaction Home §aallowed",
			error_find_faction: "§cFaction not found.",
			set_utc: "§eUTC updated.",
			mute: `§e${arguments[1]} muted`,
			unmute: `§e${arguments[1]} un-muted`,
			unwarn: `§e•> ${arguments[1]} un-warn (now at ${arguments[2]})`,
			error_unwarn: "§cPlayer has 0 warn.",
			warn: `§e${arguments[1]} warn (now at ${arguments[2]})`,
			warn_get: "§c•> You receive a warn !",
			error_find_tpayes: "§cYou don't have tpa request.",
			tpa_send: `§e•> Tpa request send to ${arguments[1]}`,
			tpa_get: `§e•> ${arguments[1]}§r§e send you a tpa request §7(do ${arguments[2]}tpayes to accept).`,
			error_tpa: "§cYou already send a tpa request to this player, please wait.",
			set_customName_off: "§eCustom Name §cOFF§e.",
			set_customName_on: "§eCustom Name §aON§e.",
			faction_add_enemy: `§e•> "${arguments[1]}" added has enemy`,
			error_set_relation: "§cYou already set relation with this faction.",
			error_faction_leader_permission: "§cOnly the leader can edit relation.",
			faction_remove_enemy: `§e•> "${arguments[1]}" removed has enemy`,
			error_not_set_relation: "§cYou didn't set relation with this faction.",
			faction_add_ally: `§e•> "${arguments[1]}" added has ally`,
			faction_remove_ally: `§e•> "${arguments[1]}" removed has ally`,
			Fopen_on: "§e•> Faction is now open to everyone who want to join.",
			Fopen_off: "§e•> Faction is now on invite only.",
			faction_demote_member: `§e•> You have demoted ${arguments[1]} to '§amember§e'`,
			faction_demote_member_get: `§e•> you have been demoted to member`,
			faction_demote_visitor: `§e•> ${arguments[1]} has been demoted to visitor`,
			faction_demote_visitor_get: `§e•> you have been demoted to visitor`,
			error_demote_visitor: `§cYou can't demote a visitor`,
			error_cant_do_that: "§cYou can't do that",
			faction_new_leader: `§e•> ${arguments[1]} is the new leader !`,
			faction_new_leader_get: "§e•> You have been demote to '§aOfficer§e'",
			faction_promote_co_leader: `§e•> ${arguments[1]} has been pomoted to Officer`,
			faction_promote_co_leader_get: `§e•> you have been pomoted to Officer`,
			faction_promote_member: `§e•> ${arguments[1]} has been pomoted to member`,
			faction_promote_member_get: `§e•> you have been pomoted to member`,
			set_prefix: `§e•> global prefix has been changed to §a${arguments[1]}`,
			error_prefix: "§cInvalid prefix.",
			error_prefix2: "§cDo not use a prefix starting with '/'",
			role_add: `§e•> Role §a${arguments[1]} §r§eadded to ${arguments[2]}.`,
			error_have_role: "§cThe player already have this role.",
			role_remove: `§e•> Role §a${arguments[1]} §r§eremoved to ${arguments[2]}.`,
			error_find_role: "§cThe player don't have this role.",
			pay: `§e•> Send §a${arguments[1]}§e to ${arguments[2]}.`,
			pay_get: `§e•> Receive §a${arguments[1]}§e from ${arguments[2]}.`,
			error_money: "§cNo enough money.",
			set_scoreMoney: `§e•> New score define : ${arguments[1]}`,
			error_name: "§cWrong Name.",
			faction_bank: `§e•> Faction Bank : ${arguments[1]}`,
			faction_bank_remove: `§e•> ${arguments[1]} transfered to you`,
			faction_bank_add: `§e•> ${arguments[1]} transfered to your faction.`,
			error_no_faction: "§cYou need to be in a faction.",
			error_bank_money: "§cNo enough money in the bank",
			error_arg_add_remove: "§cWrong Arguments (should be add | remove)",
			faction_kick: `§e•> You kick ${arguments[1]}.`,
			faction_kick_get: `§e•> You have been kick from the ${arguments[1]} faction.`,
			error_faction_kick: "§cYou can't kick this player.",
			faction_home: `§e•> f home set : §a${arguments[1]} ${arguments[2]} ${arguments[3]}`,
			error_faction_home: "§cYou can only place f home in overworld.",
			error_faction_home_off: "§cf home are disable.",
			set_memberlimit_g: `§e•> New global limit set : ${arguments[1]}`,
			set_memberlimit_l: `§e•> New member limit for ${arguments[1]} set : ${arguments[2]}`,
			warp_msg_add: `§e•> Message Added :§r\n${arguments[1]}`,
			error_find_warp: "§cWarp not found",
			warp_msg_on: "§e•> Message on tp §aON",
			warp_msg_off: "§e•> Message on tp §cOFF",
			warp_open: `§e•> ${arguments[1]} is now §aOpen`,
			warp_close: `§e•> ${arguments[1]} is now §cClose`,
			error_warp_cmd: "§cThere is no command in this warp",
			warp_cmd_clear: "§eCommand cleared",
			error_have_warp_cmd: "§cCommand already added to the warp.",
			error_arg_warp_cmd: "§cInvalid parameter",
			error_warp: `§cYou need to wait ${arguments[1]} secondes before using this warp again.`,
			error_warp_close: "§cThis warp is closed.",
			//don't edit warp_allow
			warp_remove: `§e•> Warp \"${arguments[1]}\" removed`,
			warp_add: `§e•> §a${arguments[1]} §eadded in ${arguments[2]} ${arguments[3]} ${arguments[4]}`,
			warp_list_empty: "§cthere is no warp",
			error_have_name: "§cThis name is already used.",
			faction_join: `§e•> §a${arguments[1]} join the faction !`,
			error_faction_join_full: "§cThis faction is full.",
			error_faction_join_invit: "§cNo invit from this faction.",
			error_faction_info: "§cNo info found",
			faction_info: `§eName : ${arguments[1]}\n§r§eDescription : ${arguments[2]}§r§e\nCreated : ${arguments[3]}§r§e\nMember Count : ${arguments[4]}/${arguments[5]}\n§r§eBank : ${arguments[6]}\n§r§ePower : ${arguments[7]}`,
			faction_invit_clear: "§eAll invit has been cleared.",
			error_list_invit: "§cNo invite found.",
			faction_invit: `invit send to \"${arguments[1]}\"`,
			faction_invit_get: `§e•> you have an invite from \"§r${arguments[1]}§r§e\" faction`,
			error_have_invit: "§cThis player is already invited",
			error_have_faction: "§cThis player is already in a faction",
			error_have_faction2: "§cYou already are in a faction.",
			faction_quit: `§e${arguments[1]} leave the faction.`,
			faction_quit_get: `§e•> You quit the \"§a${arguments[1]}§r§e\" faction`,
			error_faction_create: "§eplease leave your faction before create a new one",
			faction_create: `§e•> §a${arguments[1]} §e created`,
			set_homelimit_g: `§e•> New global limit set : ${arguments[1]}`,
			set_homelimit_l: `§e•> New home limit for ${arguments[1]} set : ${arguments[2]}`,
			error_have_home: "§cYou already have a home with that name.",
			error_limit_home: "§cYou have reach the limit of home you can add.",
			home_add: `§e•> "§a${arguments[1]}§e" home added.`,
			home_remove: `§e•> "§a${arguments[1]}§e" removed.`,
			admin_home_remove: `§e•> "§a${arguments[1]}§e" removed for ${arguments[2]}.`,
			error_find_home: "§cHome not found.",
			home_list: `§eHome List :${arguments[1]}`,
			error_home_list: "§cThere is no home",
			error_not_allow_command: "§cYou are not allowed to use this command",
			tpa_expire: `§8•tpa•> ${arguments[1]} ${arguments[2]} expired.`,
			spam: "§cDon't spam !",
			//your credit for making the translation :
			credit_translate: "translation by : mister art43",

			//v1.0.22
			lang: "your language has been modified",
			error_lang: "language not found",

			//v1.0.26
			private_chat_reset: "you are now back to the public chat",
			error_have_private_chat: "you are already in the public chat",
			change_private_chat: `§achat changed to ${arguments[1]} chat`,
			ec_object_added: `${arguments[1]} new object added to the list`,
			error_find_item: "No item found",
			error_unknow_item: `\nSlot : ${arguments[1]}. No item or unknown`,

			//v1.0.38
			tpahere_get: `§e•> ${arguments[1]}§r§e send you a tpahere request §7(do ${arguments[2]}tpayes to accept).`
		}
	}
	if (arguments[0] == "fr") {
		return {
			error_arg: "§cMauvais arguments",
			error_find_player: "§cJoueur non trouvé",
			db_update: "§6Base de données mise à jour",
			db_already_update: "§cBase de données déjà à jour",
			unlock_admin_db: "§eBase de données administrateur dévérouillée",
			lock_admin_db: "§eBase de données administrateur vérouillée",
			lock_error: "§cVous ne pouvez pas regarder la base de données administrateur si vous n'êtes pas administrateur",
			add_admin_error: "§cCe joueur est déjà administrateur",
			add_admin: "§eCe joueur est désormait administrateur",
			error_pass: "§cMot de passe incorrect",
			remove_admin: "§eCe joueur n'est plus administrateur",
			error_find_admin: "§cAdministrateur non trouvé",
			unban: `§e${arguments[1]} a été débanni`,
			set_tpa_delay: `§eDelai de Tpa mis à ${arguments[1]} secondes`,
			error_number: `§cNombre invalide`,
			add_display: "§eAffichage ajouté.",
			error_tag: `§cTag invalide`,
			error_arg_display: `§cMauvais arguments (devraient être "title" ou "actionbar")`,
			remove_display: `§eAffichage n°${arguments[1]} retiré.`,
			error_find_display: `§cImpossible de trouver cet affichage (faites ${arguments[1]}display list)`,
			error_number_display: `§cNombre invalide (faites ${arguments[1]}display list)`,
			error_arg_display2: `§cMauvais arguments (add|remove|list) attendu`,
			set_Fhome_off: "§eHome de faction §crefusé",
			set_Fhome_on: "§eHome de faction §aautorisé",
			error_find_faction: "§cFaction non trouvée.",
			set_utc: "§eUTC mis à jour.",
			mute: `§e${arguments[1]} a été rendu muet`,
			unmute: `§e${arguments[1]} n'est plus muet`,
			unwarn: `§e•> ${arguments[1]} a été un-warn (maintenant à ${arguments[2]})`,
			error_unwarn: "§cCe joueur a 0 warn.",
			warn: `§e${arguments[1]} a été warn (maintenant à ${arguments[2]})`,
			warn_get: "§c•> Vous avez été warn !",
			error_find_tpayes: "§cVous n'avez pas de demande de Tpa.",
			tpa_send: `§e•> Demande de Tpa envoyée à ${arguments[1]}`,
			tpa_get: `§e•> ${arguments[1]}§r§e vous a envoyé(e) une demande de Tpa §7(faites ${arguments[2]}tpayes pour accepter).`,
			error_tpa: "§cVous avez déjà envoyé(e) une demande de Tp à ce joueur, attendez s'il vous plaît.",
			set_customName_off: "§eNom personalisé §cOFF§e.",
			set_customName_on: "§eNom personalisé §aON§e.",
			faction_add_enemy: `§e•> "La faction ${arguments[1]}" a été ajoutée comme enemie`,
			error_set_relation: "§cVous avez déjà établi une relation avec cette faction.",
			error_faction_leader_permission: "§cSeulement le chef peut modifier cette relation.",
			faction_remove_enemy: `§e•> "La faction ${arguments[1]}" a été retirée des ennemis`,
			error_not_set_relation: "§cVous n'avez pas mit en place de relation avec cette faction.",
			faction_add_ally: `§e•> "La faction ${arguments[1]}" a été ajoutée comme alliée`,
			faction_remove_ally: `§e•> "La faction ${arguments[1]}" a été retirée des alliés`,
			Fopen_on: "§e•> La faction est maintenant ouverte à tous ceux qui veulent rejoindre.",
			Fopen_off: "§e•> La faction est maintenant sur invitation seulement.",
			faction_demote_member: `§e•> Vous avez rétrogradé ${arguments[1]} à '§amembre§e'`,
			faction_demote_member_get: `§e•> Vous avez été rétrogradé à membre`,
			faction_demote_visitor: `§e•> ${arguments[1]} a été rétrogradé à visiteur`,
			faction_demote_visitor_get: `§e•> Vous avez été rétrogradé à visiteur`,
			error_demote_visitor: `§cVous ne pouvez pas rétrogradé un visiteur`,
			error_cant_do_that: "§cVous ne pouvez pas faire ceci",
			faction_new_leader: `§e•> ${arguments[1]} est le nouveau chef !`,
			faction_new_leader_get: "§e•> Vous avez été rétrogradé à '§asous-chef§e'",
			faction_promote_co_leader: `§e•> ${arguments[1]} a été promu comme sous-chef`,
			faction_promote_co_leader_get: `§e•> Vous avez été promu à sous-chef`,
			faction_promote_member: `§e•> ${arguments[1]} a été promu à membre`,
			faction_promote_member_get: `§e•> Vous avez été promu à membre`,
			set_prefix: `§e•> Le préfixe global a été modifié pour §a${arguments[1]}`,
			error_prefix: "§cPréfixe invalide.",
			error_prefix2: "§cN'utilisez pas un préfixe qui commence par '/'",
			role_add: `§e•> Rôle §a${arguments[1]} §r§eajouté à ${arguments[2]}.`,
			error_have_role: "§cLe joueur a déjà ce rôle.",
			role_remove: `§e•> Rôle §a${arguments[1]} §r§eretiré à ${arguments[2]}.`,
			error_find_role: "§cLe joueur n'a pas ce rôle.",
			pay: `§e•> Vous avez envoyé §a${arguments[1]}§e à ${arguments[2]}.`,
			pay_get: `§e•> Vous avez reçu §a${arguments[1]}§e de la part de ${arguments[2]}.`,
			error_money: "§cVous n'avez pas assez d'argent.",
			set_scoreMoney: `§e•> Nouvel objectif définit à : ${arguments[1]}`,
			error_name: "§cMauvais nom.",
			faction_bank: `§e•> Banque de faction : ${arguments[1]}`,
			faction_bank_remove: `§e•> ${arguments[1]} transféré à votre compte`,
			faction_bank_add: `§e•> ${arguments[1]} transféré à votre banque de faction.`,
			error_no_faction: "§cVous devez être dans une faction.",
			error_bank_money: "§cPas assez d'argent dans la banque",
			error_arg_add_remove: "§cMauvais arguments (devraient être add | remove)",
			faction_kick: `§e•> Vous avez viré ${arguments[1]}.`,
			faction_kick_get: `§e•> Vous avez été viré de ${arguments[1]}.`,
			error_faction_kick: "§cVous ne pouvez pas virer ce joueur.",
			faction_home: `§e•> Home de faction mis à : §a${arguments[1]} ${arguments[2]} ${arguments[3]}`,
			error_faction_home: "§cVous pouvez seulement placer votre home de faction dans l'overworld.",
			error_faction_home_off: "§cLes homes de factions sont désactivés.",
			set_memberlimit_g: `§e•> La nouvelle limite globale a été mise à : ${arguments[1]}`,
			set_memberlimit_l: `§e•> La nouvelle limite de membre pour ${arguments[1]} a été mise à : ${arguments[2]}`,
			warp_msg_add: `§e•> Message ajouté :§r\n${arguments[1]}`,
			error_find_warp: "§cWarp non trouvé",
			warp_msg_on: "§e•> Message lors de la Tp §aON",
			warp_msg_off: "§e•> Message lors de la Tp §cOFF",
			warp_open: `§e•> ${arguments[1]} est maintenant §aOuvert`,
			warp_close: `§e•> ${arguments[1]} est maintenant §cFermé`,
			error_warp_cmd: "§cIl n'y a pas de commandes dans ce warp",
			warp_cmd_clear: "§eCommandes effacées",
			error_have_warp_cmd: "§cCommande déjà ajoutée au warp.",
			error_arg_warp_cmd: "§cParamètres invalides",
			error_warp: `§cVous devez attendre ${arguments[1]} secondes avant de pouvoir re-utiliser ce warp.`,
			error_warp_close: "§cCe warp est fermé.",
			//don't edit warp_allow
			warp_remove: `§e•> Le warp \"${arguments[1]}\" a été retiré`,
			warp_add: `§e•> §a${arguments[1]} §ea été ajouté à ${arguments[2]} ${arguments[3]} ${arguments[4]}`,
			warp_list_empty: "§cIl n'y a pas de warp",
			error_have_name: "§cCe nom est déjà utilisé.",
			faction_join: `§e•> §a${arguments[1]} a rejoins la faction !`,
			error_faction_join_full: "§cCette faction est complète.",
			error_faction_join_invit: "§cVous n'avez pas d'invitation de la part de cette faction.",
			error_faction_info: "§cAucunes informations trouvées",
			faction_info: `§eNom : ${arguments[1]}\n§r§eDescription : ${arguments[2]}§r§e\nCreation : ${arguments[3]}§r§e\nNombre de membres : ${arguments[4]}/${arguments[5]}\n§r§eBanque : ${arguments[6]}\n§r§ePuissance : ${arguments[7]}`,
			faction_invit_clear: "§eToutes les invitations ont été éffacées.",
			error_list_invit: "§cAucune invitation trouvée.",
			faction_invit: `Invitation envoyée à \"${arguments[1]}\"`,
			faction_invit_get: `§e•> Vous avez une invitation de la part de la faction \"§r${arguments[1]}§r§e\"`,
			error_have_invit: "§cCe joueur a déjà été invité",
			error_have_faction: "§cCe joueur est déjà dans une faction",
			error_have_faction2: "§cVous êtes déjà dans une faction.",
			faction_quit: `§e${arguments[1]} a quitté(e) la faction.`,
			faction_quit_get: `§e•> Vous avez quitté(e) la faction \"§a${arguments[1]}§r§e\"`,
			error_faction_create: "§eVeuillez quitter votre faction avant d'en créer une nouvelle",
			faction_create: `§e•> La faction §a${arguments[1]} §e a été créée`,
			set_homelimit_g: `§e•> Nouvelle limite globale de homes mise à : ${arguments[1]}`,
			set_homelimit_l: `§e•> Nouvelle limite de homes pour ${arguments[1]} mise à : ${arguments[2]}`,
			error_have_home: "§cVous avez déjà un home avec ce nom.",
			error_limit_home: "§cVous avez atteint la limite de home que vous pouvez avoir.",
			home_add: `§e•> "Le home §a${arguments[1]}§e" a été ajouté.`,
			home_remove: `§e•> "Le home §a${arguments[1]}§e" a été retiré.`,
			admin_home_remove: `§e•> "Le home §a${arguments[1]}§e" a été retiré pour ${arguments[2]}.`,
			error_find_home: "§cHome non trouvé.",
			home_list: `§eListe des homes :${arguments[1]}`,
			error_home_list: "§cVous n'avez pas de homes",
			error_not_allow_command: "§cVous n'êtes pas autorisé à utiliser cette commande",
			tpa_expire: `§8•tpa•> ${arguments[1]} ${arguments[2]} a expiré.`,
			spam: "§cNe spammez pas !",
			//your credit for making the translation :
			credit_translate: "translation by : Xbox : MEGA Minoche95 \nDiscord : Minoche95#1825 )",

			//v1.0.22
			lang: "votre langage à bien été modifié.",
			error_lang: "langage introuvable.",

			//v1.0.26
			private_chat_reset: "you are now back to the public chat",
			error_have_private_chat: "you are already in the public chat",
			change_private_chat: `§achat changed to ${arguments[1]} chat`,

			//v1.0.38
			tpahere_get: `§e•> ${arguments[1]}§r§e vous a envoyé un tpahere, (§a${arguments[2]}tpaccept§r§e pour accepter)`,
		}
	}
	if (arguments[0] == "es") {
		return {
			error_arg: "§cArgumentos Equivocados",
			error_find_player: "§cJugador no encontrado",
			db_update: "§6Base de datos actualizada",
			db_already_update: "§cBase de datos ya actualizada",
			unlock_admin_db: "§eBase de datos de administración desbloqueada",
			lock_admin_db: "§eBase de datos de administración bloqueada",
			lock_error: "§cNo se puede bloquear la base de datos de administración si no está dentro",
			add_admin_error: "§cEste jugador ya es administrador",
			add_admin: "§eJugador agregado a la base de datos de administración",
			error_pass: "§cContraseña invalida",
			remove_admin: "§eJugador eliminado de la base de datos de administración",
			error_find_admin: "§cAdministrador no encontrado",
			unban: `§e${arguments[1]} desbaneado`,
			set_tpa_delay: `§eRetardo de tpa establecido en ${arguments[1]} segundos`,
			error_number: `§cNúmero invalido`,
			add_display: "§ePantalla añadida.",
			error_tag: `§cEtiqueta inválida`,
			error_arg_display: `§cArgumentos Incorrectos (debe ser "título" o "barra de acción")`,
			remove_display: `§ePantalla n°${arguments[1]} eliminada.`,
			error_find_display: `§cNo puedo encontrar la pantalla (do ${arguments[1]}display list)`,
			error_number_display: `§cNúmero invalido (do ${arguments[1]}display list)`,
			error_arg_display2: `§cArgumentos Equivocados (add|remove|list) esperado`,
			set_Fhome_off: "§eCasa de Facciones §cdenegado",
			set_Fhome_on: "§eCasa de Facciones §apermitido",
			error_find_faction: "§cFacción no encontrada.",
			set_utc: "§eUTC actualizado.",
			mute: `§e${arguments[1]} apagado`,
			unmute: `§e${arguments[1]} no silenciado`,
			unwarn: `§e•> ${arguments[1]} advertir eliminado (now at ${arguments[2]})`,
			error_unwarn: "§cEl jugador tiene 0 advertencias.",
			warn: `§e${arguments[1]} advertir (now at ${arguments[2]})`,
			warn_get: "§c•> ¡Te han dado una advertencia!",
			error_find_tpayes: "§cNo tienes solicitud de tpa.",
			tpa_send: `§e•> Solicitud de tpa enviada a ${arguments[1]}`,
			tpa_get: `§e•> ${arguments[1]}§r§e te ha enviado una solicitud de tpa §7(hacer ${arguments[2]}tpayes aceptar).`,
			error_tpa: "§cYa enviaste una solicitud de tpa a este jugador, espera.",
			set_customName_off: "§eNombre Personalizado §cAPAGADO§e.",
			set_customName_on: "§eNombre Personalizado §aSOBRE§e.",
			faction_add_enemy: `§e•> "${arguments[1]}" enemigo añadido`,
			error_set_relation: "§cYa has establecido una relación con esta facción.",
			error_faction_leader_permission: "§cSolo la líder puede editar la relación.",
			faction_remove_enemy: `§e•> "${arguments[1]}" eliminar enemigo`,
			error_not_set_relation: "§cNo estableciste relación con esta facción.",
			faction_add_ally: `§e•> "${arguments[1]}" aliado añadido`,
			faction_remove_ally: `§e•> "${arguments[1]}" aliado eliminado`,
			Fopen_on: "§e•> La facción ahora está abierta a todos los que quieran unirse.",
			Fopen_off: "§e•> La facción ahora es solo por invitación.",
			faction_demote_member: `§e•> Tú has degradado ${arguments[1]} to '§amiembro§e'`,
			faction_demote_member_get: `§e•> Has sido degradada a miembro`,
			faction_demote_visitor: `§e•> ${arguments[1]} ha sido degradado a visitante.`,
			faction_demote_visitor_get: `§e•> Has sido degradada a visitante`,
			error_demote_visitor: `§cNo puedes degradar a una visitante`,
			error_cant_do_that: "§cUsted no puede hacer eso",
			faction_new_leader: `§e•> ${arguments[1]} es el nuevo líder!`,
			faction_new_leader_get: "§e•> Has sido degradada a '§aco líder§e'",
			faction_promote_co_leader: `§e•> ${arguments[1]} ha sido ascendido a co líder`,
			faction_promote_co_leader_get: `§e•> Usted ha sido ascendido a co líder`,
			faction_promote_member: `§e•> ${arguments[1]} ha sido promovida a miembro`,
			faction_promote_member_get: `§e•> has sido promovida a miembro`,
			set_prefix: `§e•> el prefijo global se ha cambiado a §a${arguments[1]}`,
			error_prefix: "§cPrefijo no válido.",
			error_prefix2: "§cNo use un prefijo que comience con '/'",
			role_add: `§e•> Role §a${arguments[1]} §r§eañadido a ${arguments[2]}.`,
			error_have_role: "§cLa jugadora ya tiene este papel.",
			role_remove: `§e•> Role §a${arguments[1]} §r§eremoved to ${arguments[2]}.`,
			error_find_role: "§cLa jugadora no tiene este papel.",
			pay: `§e•> Enviar §a${arguments[1]}§e a ${arguments[2]}.`,
			pay_get: `§e•> Recibir §a${arguments[1]}§e desde ${arguments[2]}.`,
			error_money: "§cDinero insuficiente.",
			set_scoreMoney: `§e•> Definición de nueva partitura : ${arguments[1]}`,
			error_name: "§Nombre Equivocado.",
			faction_bank: `§e•> Banco de Facciones : ${arguments[1]}`,
			faction_bank_remove: `§e•> ${arguments[1]} transferido a usted`,
			faction_bank_add: `§e•> ${arguments[1]} transferida a tu facción.`,
			error_no_faction: "§cTienes que estar en una facción.",
			error_bank_money: "§cNo hay suficiente dinero en el banco",
			error_arg_add_remove: "§cArgumentos Equivocados (debería ser add | remove)",
			faction_kick: `§e•> Tu pateaste ${arguments[1]}.`,
			faction_kick_get: `§e•> Te han echado de la ${arguments[1]} facción.`,
			error_faction_kick: "§cNo puedes patear a esta jugadora.",
			faction_home: `§e•> conjunto de casa de facción : §a${arguments[1]} ${arguments[2]} ${arguments[3]}`,
			error_faction_home: "§cSolo puedes colocar el hogar de la facción en el supramundo.",
			error_faction_home_off: "§cLas casas de las facciones están desactivadas",
			set_memberlimit_g: `§e•> Nuevo conjunto de límite globales : ${arguments[1]}`,
			set_memberlimit_l: `§e•> Límite de nueva miembro para ${arguments[1]} set : ${arguments[2]}`,
			warp_msg_add: `§e•> Mensaje agregado :§r\n${arguments[1]}`,
			error_find_warp: "§cUrdimbre no encontrada",
			warp_msg_on: "§e•> Mensaje en teletransporte §aSOBRE",
			warp_msg_off: "§e•> Mensaje en teletransporte §cAPAGADO",
			warp_open: `§e•> ${arguments[1]} ahora está §aAbierto`,
			warp_close: `§e•> ${arguments[1]} ahora está §cCerrada`,
			error_warp_cmd: "§cNo hay comando en esta urdimbre.",
			warp_cmd_clear: "§eComando eliminado",
			error_have_warp_cmd: "§cComando ya añadido al warp.",
			error_arg_warp_cmd: "§cParametro invalido",
			error_warp: `§cNecesitas esperar ${arguments[1]} segundos antes de usar esta urdimbre de nuevo.`,
			error_warp_close: "§cEsta urdimbre está cerrada.",
			//don't edit warp_allow
			warp_remove: `§e•> Urdimbre \"${arguments[1]}\" eliminada`,
			warp_add: `§e•> §a${arguments[1]} §eañadido en ${arguments[2]} ${arguments[3]} ${arguments[4]}`,
			warp_list_empty: "§cNo hay urdimbre",
			error_have_name: "§cEste nombre ya se usa.",
			faction_join: `§e•> §a${arguments[1]} únete a la facción!`,
			error_faction_join_full: "§cEsta facción está llena.",
			error_faction_join_invit: "§cNo hay invitación de esta facción.",
			error_faction_info: "§cNo se encontró información",
			faction_info: `§eNombre : ${arguments[1]}\n§r§eDescripción : ${arguments[2]}§r§e\nCreada : ${arguments[3]}§r§e\nMiembros : ${arguments[4]}/${arguments[5]}\n§r§eBanco : ${arguments[6]}\n§r§eFuerza : ${arguments[7]}`,
			faction_invit_clear: "§eSe han borrado todas las invitaciones.",
			error_list_invit: "§cNo se encontró ninguna invitación.",
			faction_invit: `Invitación enviada a \"${arguments[1]}\"`,
			faction_invit_get: `§e•> Tienes una invitación de \"§r${arguments[1]}§r§e\" faction`,
			error_have_invit: "§cEsta jugadora ya esta invitada",
			error_have_faction: "§cEsta jugadora ya está en una facción",
			error_have_faction2: "§cYa estás en una facción.",
			faction_quit: `§e${arguments[1]} dejó la facción.`,
			faction_quit_get: `§e•> Dejaste el \"§a${arguments[1]}§r§e\" facción`,
			error_faction_create: "§ePor favor, deja tu facción antes de crear una nueva.",
			faction_create: `§e•> §a${arguments[1]} §e creada`,
			set_homelimit_g: `§e•> Nuevo conjunto de límite globales : ${arguments[1]}`,
			set_homelimit_l: `§e•> Nuevo límite de viviendas para ${arguments[1]} set : ${arguments[2]}`,
			error_have_home: "§cYa tienes una vivienda con ese nombre.",
			error_limit_home: "§cHas alcanzado el límite de hogares que puedes crear.",
			home_add: `§e•> "§a${arguments[1]}§e" casa añadida.`,
			home_remove: `§e•> "§a${arguments[1]}§e" retirar.`,
			admin_home_remove: `§e•> "§a${arguments[1]}§e" eliminado por ${arguments[2]}.`,
			error_find_home: "§cCasa no encontrada.",
			home_list: `§eLista de casas :${arguments[1]}`,
			error_home_list: "§cNo hay hogar",
			error_not_allow_command: "§cNo tienes permiso para usar este comando.",
			tpa_expire: `§8•tpa•> ${arguments[1]} ${arguments[2]} caducada.`,
			spam: "§cDon't spam !",
			//your credit for making the translation :
			credit_translate: "Spanish Translation by HazyWinner55 >:] / Traducción al español por HazyWinner55 >:]",

			//v1.0.22
			lang: "su idioma ha sido modificado",
			error_lang: "idioma no encontrado",

			//v1.0.26
			private_chat_reset: "you are now back to the public chat",
			error_have_private_chat: "you are already in the public chat",
			change_private_chat: `§achat changed to ${arguments[1]} chat`,

			//v1.0.38
			tpahere_get: `§e•> ${arguments[1]}§r§e envió un tpahere, (§a${arguments[2]}tpaccept§r§e para aceptar)`,
		}
	}
	if (arguments[0] == "pl") {
		return {
			error_arg: "§cBłędne argumenty",
			error_find_player: "§cNie znaleziono gracza",
			db_update: "§6Baza danych zaktualizowana",
			db_already_update: "§cBaza danych już zaktualizowana",
			unlock_admin_db: "§eAdmin baza danych odblokowana",
			lock_admin_db: "§eAdmin baza danych zablokowana",
			lock_error: "§cNie możesz zablokować bazy danych administratora, jeśli nie jesteś w środku",
			add_admin_error: "§cTen gracz jest już adminem",
			add_admin: "§eGracz zostal dodany do bazy danych",
			error_pass: "§cNieprawidlowe haslo",
			remove_admin: "§eUsunieto gracza z bazy danych Admin",
			error_find_admin: "§cAdmin nie znaleziono",
			unban: `§e${arguments[1]} jest unbanowany`,
			set_tpa_delay: `§eTpa opoznienie ustawione ${arguments[1]} sekund`,
			error_number: `§cNieprawidlowa liczba`,
			add_display: "§eEkran dodany.",
			error_tag: `§cNieprawidlowy znacznik`,
			error_arg_display: `§cNieprawidlowy argument (powinien byc "title" lub "actionbar")`,
			remove_display: `§eEkran n°${arguments[1]} usunieto.`,
			error_find_display: `§cNie znaleziono ekranu (do ${arguments[1]}display list)`,
			error_number_display: `§cNie prawidlowa liczba (do ${arguments[1]}display list)`,
			error_arg_display2: `§cNieprawidlowy argument (add|remove|list) expected`,
			set_Fhome_off: "§eFrakcja dom §codmowiono",
			set_Fhome_on: "§eFrakcja dom §apozwolono",
			error_find_faction: "§cFrakcja nie znaleziona.",
			set_utc: "§eUTC zaktulizowano.",
			mute: `§e${arguments[1]} wyciszony`,
			unmute: `§e${arguments[1]} odciszony`,
			unwarn: `§e•> ${arguments[1]} usunieto ostrzezenie (posiada ${arguments[2]})`,
			error_unwarn: "§cGracz ma 0 ostrzezen.",
			warn: `§e${arguments[1]} ostrzezenie (posiada ${arguments[2]})`,
			warn_get: "§c•> Ostrzezenie!",
			error_find_tpayes: "§cNie masz prosby o tpa  .",
			tpa_send: `§e•> Prosba o tpa wyslana do ${arguments[1]}`,
			tpa_get: `§e•> ${arguments[1]}§r§e wyslal ci prosbe o tpa §7(wpisz ${arguments[2]}tpayes zeby zakceptowac).`,
			error_tpa: "§cWyslales juz prosbe do tego gracza, prosze czekac.",
			set_customName_off: "§eWlasna nazwa §cWylaczona§e.",
			set_customName_on: "§eWlasna nazwa §aWlaczona§e.",
			faction_add_enemy: `§e•> "${arguments[1]}" dodano za wroga`,
			error_set_relation: "§cTwoje relacja z ta frakcia jest juz ustawiona.",
			error_faction_leader_permission: "§cTylko lider moze edytowac ta frakcje.",
			faction_remove_enemy: `§e•> "${arguments[1]}" usunieto za wroga`,
			error_not_set_relation: "§cNie ustawiles relacij z ta frakcja.",
			faction_add_ally: `§e•> "${arguments[1]}" sojusz zostal dodany`,
			faction_remove_ally: `§e•> "${arguments[1]}" sojusz zostal rozwiazany`,
			Fopen_on: "§e•> Frakcja jest teraz otwarta dla wszystkich.",
			Fopen_off: "§e•> Frakcja jest teraz otwarta tylko z zaproszeniem.",
			faction_demote_member: `§e•> Zdegradowales ${arguments[1]} do '§amember§e'`,
			faction_demote_member_get: `§e•> Zostales zdegradowany do gracza`,
			faction_demote_visitor: `§e•> ${arguments[1]} zostal zdegradowany do obserwatora`,
			faction_demote_visitor_get: `§e•> zostales zdegradowany do obserwatora`,
			error_demote_visitor: `§cNie mozesz zdegradowac obserwatora`,
			error_cant_do_that: "§cNie mozesz tego zrobic",
			faction_new_leader: `§e•> ${arguments[1]} jest nowym liderem !`,
			faction_new_leader_get: "§e•>Zostales zdegradowany do rangi'§aOfficer§e'",
			faction_promote_co_leader: `§e•> ${arguments[1]} awansowal na lidera`,
			faction_promote_co_leader_get: `§e•> awansowales na wspol lidera`,
			faction_promote_member: `§e•> ${arguments[1]} jest od teraz czlonkiem`,
			faction_promote_member_get: `§e•> awansowales na czlonka`,
			set_prefix: `§e•> globalny prefiks został zmieniony na §a${arguments[1]}`,
			error_prefix: "§cNieprawidlowy prefix.",
			error_prefix2: "§cNie uzywaj prefixu zaczynajacego sie od '/'",
			role_add: `§e•> Rola §a${arguments[1]} §r§edodana do ${arguments[2]}.`,
			error_have_role: "§cTen gracz ma juz ta role.",
			role_remove: `§e•> Rola §a${arguments[1]} §r§eusunieto do ${arguments[2]}.`,
			error_find_role: "§cTen gracz nie ma tej roli.",
			pay: `§e•> Wyslano §a${arguments[1]}§e do ${arguments[2]}.`,
			pay_get: `§e•> Otrzymales §a${arguments[1]}§e od ${arguments[2]}.`,
			error_money: "§cBrak wystarczajaco pieniedzy.",
			set_scoreMoney: `§e•> Nowa wartosc ustawiona : ${arguments[1]}`,
			error_name: "§cZla nazwa.",
			faction_bank: `§e•> Frakcjia bank : ${arguments[1]}`,
			faction_bank_remove: `§e•> ${arguments[1]} przeslano do ciebie`,
			faction_bank_add: `§e•> ${arguments[1]} przeslano do twojej frakji.`,
			error_no_faction: "§cMusisz byc we frakcji.",
			error_bank_money: "§cBrak wystarczajacej sumy w banku",
			error_arg_add_remove: "§cZly argument (powinien byc add | remove)",
			faction_kick: `§e•> Wyrzuciles ${arguments[1]}.`,
			faction_kick_get: `§e•> Zostales wyrzucony z ${arguments[1]} frakcji.`,
			error_faction_kick: "§cNie mozna wyrzucic gracza.",
			faction_home: `§e•> f home ustawiono : §a${arguments[1]} ${arguments[2]} ${arguments[3]}`,
			error_faction_home: "§cMozesz postwaic f home tylko w overworldzie.",
			error_faction_home_off: "§cf Domy sa wylaczone.",
			set_memberlimit_g: `§e•> Nowy globalny limit : ${arguments[1]}`,
			set_memberlimit_l: `§e•> Nowy limit czlonkow  ${arguments[1]} ustawiono na : ${arguments[2]}`,
			warp_msg_add: `§e•> Wiadomosc dodana :§r\n${arguments[1]}`,
			error_find_warp: "§cWarp nie znaleziono",
			warp_msg_on: "§e•> Wiadomosci na tp §awlaczono",
			warp_msg_off: "§e•> Wiadomosci na tp §cwylaczono",
			warp_open: `§e•> ${arguments[1]} jest teraz §aOtwarta`,
			warp_close: `§e•> ${arguments[1]} jest teraz §cZamknieta`,
			error_warp_cmd: "§cBrak polecen w tym wrap",
			warp_cmd_clear: "§ePolecenie usuniete",
			error_have_warp_cmd: "§cPolecenie zostalo juz dodane do tego warp.",
			error_arg_warp_cmd: "§cNieprawidlowy parametr",
			error_warp: `§cMusisz poczekac ${arguments[1]} sekund przed ponownym uzyciem.`,
			error_warp_close: "§cTen warp zostal usuniety.",
			//don't edit warp_allow
			warp_remove: `§e•> Warp \"${arguments[1]}\" usuniety`,
			warp_add: `§e•> §a${arguments[1]} §edodany do ${arguments[2]} ${arguments[3]} ${arguments[4]}`,
			warp_list_empty: "§cLista warp jest pusta",
			error_have_name: "§cTa nazwa zosatala juz zuzyta.",
			faction_join: `§e•> §a${arguments[1]} dolaczono do frakci !`,
			error_faction_join_full: "§cTa frakcja jest juz pelna.",
			error_faction_join_invit: "§cBrak zaproszen do tej frakci.",
			error_faction_info: "§cBrak informaci",
			faction_info: `§eNazwa : ${arguments[1]}\n§r§eOpis : ${arguments[2]}§r§e\nStworzona : ${arguments[3]}§r§e\nMember Count : ${arguments[4]}/${arguments[5]}\n§r§eBank : ${arguments[6]}\n§r§ePower : ${arguments[7]}`,
			faction_invit_clear: "§eWszystkie zaproszenia zostaly wyczyszczone.",
			error_list_invit: "§cBrak zaproszen.",
			faction_invit: `Zaproszenie wyslane do \"${arguments[1]}\"`,
			faction_invit_get: `§e•> zostales zaproszony do \"§r${arguments[1]}§r§e\" frakcji`,
			error_have_invit: "§cTen gracz jest juz zaproszony",
			error_have_faction: "§cTen gracz zostal juz zaproszony",
			error_have_faction2: "§cJestes juz we frakji.",
			faction_quit: `§e${arguments[1]} Opuszcza frakjie.`,
			faction_quit_get: `§e•> Opusciles frakcjie \"§a${arguments[1]}§r§e\"`,
			error_faction_create: "§eOpusc frakije przed stworzeniem nowej",
			faction_create: `§e•> §a${arguments[1]} §e stworzono`,
			set_homelimit_g: `§e•> Nowy globalny limit ustawiono : ${arguments[1]}`,
			set_homelimit_l: `§e•> Nowy dom limit ${arguments[1]} ustawiono : ${arguments[2]}`,
			error_have_home: "§cMasz juz dom o tej nazwie.",
			error_limit_home: "§cOsiagnoles juz limit domow.",
			home_add: `§e•> "§a${arguments[1]}§e" dom dodany.`,
			home_remove: `§e•> "§a${arguments[1]}§e" usunieto.`,
			admin_home_remove: `§e•> "§a${arguments[1]}§e" usunieto dla ${arguments[2]}.`,
			error_find_home: "§cDom nie znaleziono.",
			home_list: `§eLista domow :${arguments[1]}`,
			error_home_list: "§cNie ma tutaj domu",
			error_not_allow_command: "§cNie masz permisji do tego polecenia",
			tpa_expire: `§8•tpa•> ${arguments[1]} ${arguments[2]} wygasa.`,
			spam: "§cNie spam!",
			//your credit for making the translation :
			credit_translate: "przetlumaczono przez Mavik : \nDiscord : Mavik#0001",

			//v1.0.22
			lang: "twoj jezyk zostal zmieniony.",
			error_lang: "nie znaleziono jezyka.",

			//v1.0.26
			private_chat_reset: "you are now back to the public chat",
			error_have_private_chat: "you are already in the public chat",
			change_private_chat: `§achat changed to ${arguments[1]} chat`,

			//v1.0.38
			tpahere_get: `§e•> ${arguments[1]}§r§e send you a tpahere request §7(do ${arguments[2]}tpayes to accept).`
		}
	}
	if (arguments[0] == "id") {
		return {
			error_arg: "§cArgumen Salah",
			error_find_player: "§cPemain Tidak Ditemukan",
			db_update: "§6Basisdata Diperbarui",
			db_already_update: "§cBasisdata sudah diperbarui",
			unlock_admin_db: "§eBasisdata Admin Terbuka",
			lock_admin_db: "§eBasisdata Admin Terkunci",
			lock_error: "§cKamu tidak dapat mengunci basisdata admin karena namamu tidak ada di basisdata Admin",
			add_admin_error: "§cPemain ini telah menjadi Admin",
			add_admin: "§ePemain ditambahkan ke basisdata Admin",
			error_pass: "§cSandi tidak valid",
			remove_admin: "§ePemain dihapus dari basisdata Admin",
			error_find_admin: "§cAdmin tidak ditemukan",
			unban: `§e${arguments[1]} di unban`,
			set_tpa_delay: `§eDelay tpa diatur ke ${arguments[1]} detik`,
			error_number: `§cAngka tidak valid`,
			add_display: "§eTampilan Ditambahkan.",
			error_tag: `§cTag tidak valid`,
			error_arg_display: `§cArgumen Salah (seharusnya "title" atau "actionbar")`,
			remove_display: `§eTampilan n°${arguments[1]} dihapus.`,
			error_find_display: `§cTidak dapat menemukan tampilan (ketik ${arguments[1]}display list)`,
			error_number_display: `§cAngka tidak valid (ketik ${arguments[1]}display list)`,
			error_arg_display2: `§cArgumen Salah, ketik salah satu dari (add|remove|list)`,
			set_Fhome_off: "§eFaction Home §cditolak",
			set_Fhome_on: "§eFaction Home §aditerima",
			error_find_faction: "§cFaction tidak ditemukan.",
			set_utc: "§eUTC diperbarui.",
			mute: `§e${arguments[1]} dibisukan`,
			unmute: `§e${arguments[1]} batal dibisukan`,
			unwarn: `§e•> ${arguments[1]} menghapus peringatan (sekarang di ${arguments[2]})`,
			error_unwarn: "§cPemain memiliki 0 peringatan.",
			warn: `§e${arguments[1]} diperingatkan (sekarang di ${arguments[2]})`,
			warn_get: "§c•> Kamu menerima peringatan !",
			error_find_tpayes: "§cKamu tidak memiliki permintaan tpa.",
			tpa_send: `§e•> Permintaan tpa dikirimkan ke ${arguments[1]}`,
			tpa_get: `§e•> ${arguments[1]}§r§e mengirimmu permintaan tpa §7(ketik ${arguments[2]}tpayes untuk menerima).`,
			error_tpa: "§cKamu sebelumnya sudah mengirimkan permintaan tpa, mohon tunggu.",
			set_customName_off: "§eCustom Name §cMATI§e.",
			set_customName_on: "§eCustom Name §aAKTIF§e.",
			faction_add_enemy: `§e•> "${arguments[1]}" ditambahkan menjadi musuh`,
			error_set_relation: "§cKamu sebelumnya sudah menjalin hubungan dengan faction ini.",
			error_faction_leader_permission: "§cHanya pemimpin yang dapat mengubah hubungan.",
			faction_remove_enemy: `§e•> "${arguments[1]}" dihapus dari musuh`,
			error_not_set_relation: "§cKamu tidak dapat menjalin hubungan dengan faction ini.",
			faction_add_ally: `§e•> "${arguments[1]}" ditambahkan menjadi sekutu`,
			faction_remove_ally: `§e•> "${arguments[1]}" dihapus dari sekutu`,
			Fopen_on: "§e•> Faction ini sekarang terbuka bagi semua orang yang ingin bergabung.",
			Fopen_off: "§e•> Faction ini sekarang hanya menerima jalur undangan.",
			faction_demote_member: `§e•> Pangkatmu diturunkan dari ${arguments[1]} menjadi '§aanggota§e'`,
			faction_demote_member_get: `§e•> pangkatmu telah diturunkan menjadi anggota`,
			faction_demote_visitor: `§e•> ${arguments[1]} diturunkan pangkat menjadi pengunjung`,
			faction_demote_visitor_get: `§e•> pangkatmu telah diturunkan menjadi pengunjung`,
			error_demote_visitor: `§cKamu tidak dapat lagi menurunkan pangkat pengunjung`,
			error_cant_do_that: "§cKamu tidak dapat melakukan hal itu",
			faction_new_leader: `§e•> ${arguments[1]} sekarang adalah pemimpin !`,
			faction_new_leader_get: "§e•> Pangkatmu telah diturunkan menjadi '§awakil pemimpin§e'",
			faction_promote_co_leader: `§e•> ${arguments[1]} telah dinaikan pangkat menjadi wakil pemimpin`,
			faction_promote_co_leader_get: `§e•> pangkatmu telah dinaikan menjadi wakil pemimpin`,
			faction_promote_member: `§e•> ${arguments[1]} telah dinaikan pangkat menjadi anggota`,
			faction_promote_member_get: `§e•> pangkatmu telah dinaikan menjadi anggota`,
			set_prefix: `§e•> prefix sedunia telah diubah menjadi §a${arguments[1]}`,
			error_prefix: "§cPrefix tidak valid.",
			error_prefix2: "§cJangan gunakan prefix dengan awalan '/'",
			role_add: `§e•> Role §a${arguments[1]} §r§editambahkan menjadi ${arguments[2]}.`,
			error_have_role: "§cPemain telah mendapatkan role ini.",
			role_remove: `§e•> Role §a${arguments[1]} §r§edihapus menjadi ${arguments[2]}.`,
			error_find_role: "§cPemaim tidak memiliki role ini.",
			pay: `§e•> Membayar §a${arguments[1]}§e ke ${arguments[2]}.`,
			pay_get: `§e•> Menerima §a${arguments[1]}§e dari ${arguments[2]}.`,
			error_money: "§cTidak cukup uang.",
			set_scoreMoney: `§e•> Skor definisi baru : ${arguments[1]}`,
			error_name: "§cNama salah.",
			faction_bank: `§e•> Faction Bank : ${arguments[1]}`,
			faction_bank_remove: `§e•> ${arguments[1]} ditransfer kepadamu`,
			faction_bank_add: `§e•> ${arguments[1]} ditransfer ke factionmu.`,
			error_no_faction: "§cKamu perlu memasuki sebuah faction.",
			error_bank_money: "§cTidak cukup uang dalam bank",
			error_arg_add_remove: "§cArgumen salah (ketik salah satu dari add | remove)",
			faction_kick: `§e•> Kamu Dikeluarkan ${arguments[1]}.`,
			faction_kick_get: `§e•> Kamu telah dikeluarkan dari ${arguments[1]} faction.`,
			error_faction_kick: "§cKamu tidak dapat mengeluarkan pemain ini.",
			faction_home: `§e•> f home diatur di : §a${arguments[1]} ${arguments[2]} ${arguments[3]}`,
			error_faction_home: "§cKamu hanya boleh f home di dunia nyata.",
			error_faction_home_off: "§cf home dinonaktifkan.",
			set_memberlimit_g: `§e•> Batas baru keanggotaan sedunia diatur ke : ${arguments[1]}`,
			set_memberlimit_l: `§e•> Batas baru keanggotaan dari ${arguments[1]} diatur ke : ${arguments[2]}`,
			warp_msg_add: `§e•> Pesan Ditambahkan :§r\n${arguments[1]}`,
			error_find_warp: "§cWarp tidak ditemukan",
			warp_msg_on: "§e•> Pesan ketika tp §aAKTIF",
			warp_msg_off: "§e•> Pesan ketika tp §cMATI",
			warp_open: `§e•> ${arguments[1]} sekarang sudah §aDibuka`,
			warp_close: `§e•> ${arguments[1]} sekatang sudah §cDitutup`,
			error_warp_cmd: "§cTidak ada perintah yang ditujukan untuk warp ini",
			warp_cmd_clear: "§ePerintah dibersihkan",
			error_have_warp_cmd: "§cPerintah sebelumnya sudah ditambahkan pada warp itu.",
			error_arg_warp_cmd: "§cParameter tidak valid",
			error_warp: `§cKamu harus menunggu ${arguments[1]} detik sebelum menggunakan warp ini kembali.`,
			error_warp_close: "§cWarp ini ditutup.",
			//don't edit warp_allow
			warp_remove: `§e•> Warp \"${arguments[1]}\" dihapus`,
			warp_add: `§e•> §a${arguments[1]} §editambahkan pada ${arguments[2]} ${arguments[3]} ${arguments[4]}`,
			warp_list_empty: "§ctidak ada warp yang tersedia",
			error_have_name: "§cNama ini sebelumnya telah digunakan.",
			faction_join: `§e•> §a${arguments[1]} bergabung kedalam faction !`,
			error_faction_join_full: "§cFaction ini sudah penuh.",
			error_faction_join_invit: "§cTidak ada undangan masuk dari faction ini.",
			error_faction_info: "§cTidak ada informasi",
			faction_info: `§eNama : ${arguments[1]}\n§r§eDescription : ${arguments[2]}§r§e\nDibuat pada : ${arguments[3]}§r§e\nJumlah anggota : ${arguments[4]}/${arguments[5]}\n§r§eBank : ${arguments[6]}\n§r§eKekuatan : ${arguments[7]}`,
			faction_invit_clear: "§eSemua undangan telah dibersihkan.",
			error_list_invit: "§cTidak ada undangan ditemukan.",
			faction_invit: `undangan dikirimkan kepada \"${arguments[1]}\"`,
			faction_invit_get: `§e•> kamu menerima undangan dari faction \"§r${arguments[1]}§r§e\"`,
			error_have_invit: "§cPemain ini sebelumnya telah diundang",
			error_have_faction: "§cPemain ini telah berada dalam faction",
			error_have_faction2: "§cKamu telah berada dalam sebuah faction.",
			faction_quit: `§e${arguments[1]} meninggalkan faction.`,
			faction_quit_get: `§e•> Kamu keluar dari faction \"§a${arguments[1]}§r§e\"`,
			error_faction_create: "§etolong keluar dari faction kamu sekarang sebelum membuat yang baru",
			faction_create: `§e•> §a${arguments[1]} §e dibuat`,
			set_homelimit_g: `§e•> Batas home sedunia diatur ke : ${arguments[1]}`,
			set_homelimit_l: `§e•> Batas home baru untuk ${arguments[1]} diatur ke : ${arguments[2]}`,
			error_have_home: "§cKamu telah memiliki home dengan nama itu.",
			error_limit_home: "§cKamu Telah mencapai batas maksimal dari home yang dapat kamu tambahkan.",
			home_add: `§e•> "§a${arguments[1]}§e" home ditambahkan.`,
			home_remove: `§e•> "§a${arguments[1]}§e" dihapus.`,
			admin_home_remove: `§e•> "§a${arguments[1]}§e" dihapuskan untuk ${arguments[2]}.`,
			error_find_home: "§cHome tidak ditemukan.",
			home_list: `§eDaftar Home :${arguments[1]}`,
			error_home_list: "§cKamu tidak memiliki home",
			error_not_allow_command: "§cKamu tidak diizinkan untuk menggunakan perintah ini",
			tpa_expire: `§8•tpa•> ${arguments[1]} ${arguments[2]} telah usang.`,
			spam: "§cJangan nyampah !",
			//your credit for making the translation :
			credit_translate: "DeesjeDeesje",

			//v1.0.22
			lang: "bahasamu telah dimodifikasi",
			error_lang: "bahasa tidak ditemukan",

			//v1.0.26
			private_chat_reset: "you are now back to the public chat",
			error_have_private_chat: "you are already in the public chat",
			change_private_chat: `§achat changed to ${arguments[1]} chat`,

			//v1.0.38
			tpahere_get: `§e•> ${arguments[1]}§r§e send you a tpahere request §7(do ${arguments[2]}tpayes to accept).`
		}
	}
	if (arguments[0] == "vi") {
		return {
			error_arg: "§cLập luận sai",
			error_find_player: "§cKhông tìm thấy trình phát",
			db_update: "§6Đã cập nhật cơ sở dữ liệu",
			db_already_update: "§cCơ sở dữ liệu đã được cập nhật",
			unlock_admin_db: "§eĐã mở khóa cơ sở dữ liệu quản trị viên",
			lock_admin_db: "§eCơ sở dữ liệu quản trị viên bị khóa",
			lock_error: "§cBạn không thể khóa cơ sở dữ liệu quản trị nếu bạn không ở trong",
			add_admin_error: "§cNgười chơi này đã là Quản trị viên",
			add_admin: "§eTrình phát được thêm vào cơ sở dữ liệu Quản trị viên",
			error_pass: "§cMật khẩu không hợp lệ",
			remove_admin: "§eTrình phát đã bị xóa khỏi cơ sở dữ liệu Quản trị viên",
			error_find_admin: "§cKhông tìm thấy quản trị viên",
			unban: `§e${arguments[1]} được bỏ cấm`,
			set_tpa_delay: `§eĐộ trễ Tpa được đặt thành ${arguments[1]} giây`,
			error_number: `§cSố không hợp lệ`,
			add_display: "§eĐã thêm hiển thị.",
			error_tag: `§cThẻ không hợp lệ`,
			error_arg_display: `§cĐối số sai (phải là "tiêu đề" hoặc "thanh hành động")`,
			remove_display: `§eTrưng bày n°${arguments[1]} loại bỏ.`,
			error_find_display: `§cKhông thể tìm thấy màn hình (làm ${arguments[1]}danh sách hiển thị)`,
			error_number_display: `§cSố không hợp lệ (làm ${arguments[1]}danh sách hiển thị)`,
			error_arg_display2: `§cĐối số sai (thêm | xóa | danh sách) được mong đợi`,
			set_Fhome_off: "§eTrang chủ phe phái §cbị từ chối",
			set_Fhome_on: "§eTrang chủ phe phái §ađược phép",
			error_find_faction: "§cKhông tìm thấy phe phái.",
			set_utc: "§eUTC được cập nhật.",
			mute: `§e${arguments[1]} tắt tiếng`,
			unmute: `§e${arguments[1]} không bị tắt tiếng`,
			unwarn: `§e•> ${arguments[1]} không được cảnh báo (bây giờ ở${arguments[1]})`,
			error_unwarn: "§cNgười chơi có 0 cảnh báo.",
			warn: `§e${arguments[1]} cảnh báo (hiện tại ${arguments[2]})`,
			warn_get: "§c•> Bạn đã nhận được một cảnh báo!",
			error_find_tpayes: "§cBạn không có yêu cầu tpa.",
			tpa_send: `§e•> Yêu cầu Tpa được gửi tới ${arguments[1]}`,
			tpa_get: `§e•> ${arguments[1]}§r đã gửi cho bạn một yêu cầu tpa §7 (làm ${aarguments[2]}trả tiền để chấp nhận).`,
			error_tpa: "§cBạn đã gửi một yêu cầu tpa tới trình phát này, vui lòng đợi.",
			set_customName_off: "§eTên tùy chỉnh §cOFF§e.",
			set_customName_on: "§eTên tùy chỉnh §aON§e.",
			faction_add_enemy: `§e•> "${arguments[1]}" được thêm vào như kẻ thù`,
			error_set_relation: "§cBạn đã thiết lập mối quan hệ với phe này.",
			error_faction_leader_permission: "§cChỉ người lãnh đạo mới có thể chỉnh sửa mối quan hệ.",
			faction_remove_enemy: `§e•> "${arguments[1]}" bị loại bỏ như kẻ thù`,
			error_not_set_relation: "§cBạn đã không thiết lập mối quan hệ với phe này.",
			faction_add_ally: `§e•> "${arguments[1]}" được thêm vào với tư cách là đồng minh`,
			faction_remove_ally: `§e•> "${arguments[1]}" loại bỏ với tư cách là đồng minh`,
			Fopen_on: "§e•> Faction hiện mở cho tất cả những ai muốn tham gia.",
			Fopen_off: "§e•> Faction hiện chỉ được mời.",
			faction_demote_member: `§e•> Bạn đã bị giáng cấp ${arguments[1]} đến '§athành viên§e'`,
			faction_demote_member_get: `§e•> bạn đã bị giáng cấp xuống thành viên`,
			faction_demote_visitor: `§e•> ${arguments[1]} đã bị giáng cấp thành khách truy cập`,
			faction_demote_visitor_get: `§e•> bạn đã bị hạ cấp thành khách truy cập`,
			error_demote_visitor: `§cBạn không thể hạ cấp một khách truy cập`,
			error_cant_do_that: "§cBạn không thể làm điều đó",
			faction_new_leader: `§e•> ${arguments[1]} là nhà lãnh đạo mới!`,
			faction_new_leader_get: "§e•> Bạn đã bị giáng cấp xuống 'lãnh đạo §aco§e'",
			faction_promote_co_leader: `§e•> ${arguments[1]} đã được thăng chức lên đồng lãnh đạo`,
			faction_promote_co_leader_get: `§e•> bạn đã được thăng chức lên đồng lãnh đạo`,
			faction_promote_member: `§e•> ${arguments[1]} đã được thăng cấp thành thành viên`,
			faction_promote_member_get: `§e•> bạn đã được thăng cấp thành thành viên`,
			set_prefix: `§e•> tiền tố toàn cầu đã được thay đổi thành §a${arguments[1]}`,
			error_prefix: "§cTiền tố không hợp lệ.",
			error_prefix2: "§cKhông sử dụng tiền tố bắt đầu bằng '/'",
			role_add: `§e•> Vai diễn §a${arguments[1]} §r§eđược thêm vào ${arguments[2]}.`,
			error_have_role: "§cNgười chơi này đã có vai trò này.",
			role_remove: `§e•> Vai diễn §a${arguments[1]} §r§ebị loại khỏi ${arguments[2]}.`,
			error_find_role: "§cNgười chơi này không có vai trò này.",
			pay: `§e•> Đã gửi §a${arguments[1]}§e đến ${arguments[2]}.`,
			pay_get: `§e•> Nhận §a${arguments[1]}§e từ ${arguments[2]}.`,
			error_money: "§cKhông đủ tiền.",
			set_scoreMoney: `§e•> Điểm số mới xác định : ${arguments[1]}`,
			error_name: "§cSai tên.",
			faction_bank: `§e•> Ngân hàng phe phái : ${arguments[1]}`,
			faction_bank_remove: `§e•> ${arguments[1]} chuyển giao cho bạn`,
			faction_bank_add: `§e•> ${arguments[1]} chuyển giao cho phe của bạn.`,
			error_no_faction: "§cBạn cần phải ở trong một phe.",
			error_bank_money: "§cKhông đủ tiền trong ngân hàng",
			error_arg_add_remove: "§cĐối số sai (nên thêm | xóa)",
			faction_kick: `§e•> Bạn đá ${arguments[1]}.`,
			faction_kick_get: `§e•> Bạn đã bị đá từ ${arguments[1]} phe phái.`,
			error_faction_kick: "§cBạn không thể đá người chơi này.",
			faction_home: `§e•> nhóm nhà thiết lập : §a${arguments[1]} ${arguments[2]} ${arguments[3]}`,
			error_faction_home: "§cBạn chỉ có thể đặt phe về nhà trong thế giới ngầm.",
			error_faction_home_off: "§cNhà của phe phái bị quản trị viên vô hiệu hóa.",
			set_memberlimit_g: `§e•> Bộ giới hạn toàn cầu mới : ${arguments[1]}`,
			set_memberlimit_l: `§e•> Giới hạn thành viên mới cho ${arguments[1]} đặt : ${arguments[3]}`,
			warp_msg_add: `§e•> Đã thêm tin nhắn :§r\n${arguments[1]}`,
			error_find_warp: "§cKhông tìm thấy sợi dọc",
			warp_msg_on: "§e•> Tin nhắn trên tp §aON",
			warp_msg_off: "§e•> Tin nhắn trên tp §cOFF",
			warp_open: `§e•> ${arguments[1]} bây giờ §aOpened`,
			warp_close: `§e•> ${arguments[1]} bây giờ đã được tiết lộ`,
			error_warp_cmd: "§cKhông có lệnh nào trong sợi dọc này",
			warp_cmd_clear: "§eĐã xóa lệnh",
			error_have_warp_cmd: "§cLệnh đã được thêm vào sợi dọc.",
			error_arg_warp_cmd: "§cTham số không hợp lệ",
			error_warp: `§cBạn cần đợi ${arguments[1]} vài giây trước khi sử dụng lại sợi dọc này.`,
			error_warp_close: "§csợi dọc này đã đóng lại.",
			//don't edit warp_allow
			warp_remove: `§e•> Làm cong \"${arguments[1]}\" loại bỏ`,
			warp_add: `§e•> §a${arguments[1]} §ethêm vào ${arguments[2]} ${arguments[3]} ${arguments[4]}`,
			warp_list_empty: "§ckhông có sợi dọc----------------",
			error_have_name: "§cTên này đã được sử dụng.",
			faction_join: `§e•> §a${arguments[1]} tham gia phe!`,
			error_faction_join_full: "§cPhe này có đầy đủ.",
			error_faction_join_invit: "§cKhông có lời mời nào từ phe này.",
			error_faction_info: "§cKhông tìm thấy thông tin",
			faction_info: `§eTên : ${arguments[1]}\n§r§eSự miêu tả : ${arguments[2]}§r§e\nTạo : ${arguments[3]}§r§e\nSố lượng thành viên : ${arguments[4]}/${arguments[5]}\n§r§eNgân hàng : ${arguments[6]}\n§r§eQuyền lực : ${arguments[7]}`,
			faction_invit_clear: "§eTất cả lời mời đã được xóa.",
			error_list_invit: "§cKhông tìm thấy lời mời.",
			faction_invit: `lời mời được gửi đến \"${arguments[1]}\"`,
			faction_invit_get: `§e•> bạn có một lời mời từ \"§r${arguments[1]}§r§e\" phe phái`,
			error_have_invit: "§cNgười chơi này đã được mời",
			error_have_faction: "§cNgười chơi này đã tham gia một phe",
			error_have_faction2: "§cBạn đã ở trong một phe.",
			faction_quit: `§e${arguments[1]} rời bỏ phe phái.`,
			faction_quit_get: `§e•> Bạn đã thoát khỏi \"§a${arguments[1]}§r§e\" phe phái`,
			error_faction_create: "§evui lòng rời khỏi nhóm của bạn trước khi tạo một nhóm mới",
			faction_create: `§e•> §a${arguments[1]} §etạo`,
			set_homelimit_g: `§e•> Bộ giới hạn toàn cầu mới : ${arguments[1]}`,
			set_homelimit_l: `§e•>Giới hạn nhà mới cho ${arguments[1]} đặt : ${arguments[1]}`,
			error_have_home: "§cBạn đã có một ngôi nhà với tên đó.",
			error_limit_home: "§cBạn đã đạt đến giới hạn số nhà mà bạn có thể thêm vào.",
			home_add: `§e•> "§a${arguments[1]}§e" thêm nhà.`,
			home_remove: `§e•> "§a${arguments[1]}§e" loại bỏ.`,
			admin_home_remove: `§e•> "§a${arguments[1]}§e" loại bỏ cho ${arguments[2]}.`,
			error_find_home: "§cKhông tìm thấy nhà.",
			home_list: `§eDanh sách Trang chủ :${arguments[1]}`,
			error_home_list: "§cKhông có nhà",
			error_not_allow_command: "§cBạn không được phép sử dụng lệnh này",
			tpa_expire: `§8•tpa•> ${arguments[1]} ${arguments[2]} hết hạn.`,
			spam: "§cĐừng spam!",
			//your credit for making the translation :
			credit_translate: "dịch bởi: Bởi Walker 90499 # 2120",

			//v1.0.26
			lang: "ngôn ngữ của bạn đã được sửa đổi",
			error_lang: "ngôn ngữ không được tìm thấy",

			//v1.0.38
			tpahere_get: `§e•> ${arguments[1]}§r§e send you a tpahere request §7(do ${arguments[2]}tpayes to accept).`
		}
	}
}